Repository gvwilson/browsercast, pull requests merged in 2025-03, with the labels that each got.

#27 Added new storyboard sketches and feedback for the presenter and viewer modes
  design/feature4.5-desktop.jpg
  design/feature4.5-mobile.png
  design/index.md
Labels: in-docs, pr-feature

#30 Added audio icon to the slide thumbnails
  v2/preview.css
  v2/preview.js
Labels: in-code, pr-feature

#28 manually loaded audio to fix forwarding issue
  v2/audio.js
Labels: in-code, pr-fix

#34 Added basic autoplay functionalities
  v2/audio.css
  v2/autoplay.css
  v2/autoplay.js
  v2/index.html
  v2/preview.css
  v2/slides.js
Labels: in-code, pr-feature

#37 Autoplay hover animation
  v2/audio.js
  v2/autoplay.js
  v2/index.html
  v2/slides.js
Labels: in-code, issue-feature, pr-feature

#38 Added autoplay scrolling
  v2/autoplay.js
  v2/preview.js
  v2/slides.css
  v2/slides.js
Labels: in-code, issue-feature

#39 Updated autoplay behavior and slide content
  v2/autoplay.css
  v2/autoplay.js
  v2/index.html
  v2/slide-images/flowerfrog.jpg
  v2/slide-images/froglifecycle.jpg
  v2/slide-images/goliathfrog.jpg
  v2/slide-images/sittingfrog.jpg
  v2/slides.css
  v2/slides.js
Labels: in-code, issue-feature, pr-feature

#42 Fixed autoplay re-enabling issue
  v2/autoplay.js
Labels: pr-fix
